config/routes.rb
Rails.application.routes.draw do
  root 'statistics#new'

  resources :statistics, only: [:new, :show, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/statistic.rb
class Statistic < ApplicationRecord
  scope :first_statistic, -> { where(id: 1).first_or_create! }

  def change_statistic(status, choice1, choice2)
    if choice1 == choice2
      self.num_not_change += 1
      if status == :won
        self.num_not_change_won += 1
      end
    else
      self.num_change += 1
      if status == :won
        self.num_change_won += 1
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def new
    @game = set_game.shuffle!
    session[:game] = @game
  end

  def show
    @game = session[:game]
    choice2 = params[:id].to_i
    choice1 = session[:choice1]

    @statistic = Statistic.first_statistic

    @status = game_status(@game, choice2)

    @statistic.change_statistic(@status, choice1, choice2)

    @statistic.save!
  end

  def edit
    @choice1 = params[:id].to_i
    @game = session[:game]
    @open_door = choose_door(@choice1)

    session[:choice1] = @choice1
  end

  private

  def set_game
    ['goat', 'goat', 'money']
  end

  def choose_door(choice)
    @game.each_with_index do |value, i|
      unless i == choice
        if value == 'goat'
          return i
        end
      end
    end
  end

  def game_status(game, choice)
    if game[choice] == 'money'
      :won
    else
      :fail
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def calc_percent(num, num_won)
    (num_won.to_f/num.to_f*100).round(2)
  end
end

app/helpers/statistic_helper.rb
module StatisticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Monty" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="/">Парадокс Монти Холла</a>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <br />
      <footer>
        <p>&copy; KarinaTiurina 2017</p>
      </footer>
    </div> <!-- /container -->

  </body>
</html>

app/views/statistics/edit.html.erb
<p>За дверью №<%= @open_door + 1 %> козa. Изменятся ли ваши шансы выиграть деньги, если вы измените ваш выбор?</p>

<h1>Ваш выбор:</h1>
<br />
<% @game.each_with_index do |value, i|%>
  <% if @open_door == i %>
    <%= image_tag('goat.jpg', :class => "item-img") %>
  <% else %>
    <%= link_to image_tag('door.jpg', :class => "item-img"), statistic_path(i) %>
  <% end %>
<% end %>

app/views/statistics/new.html.erb
<p>Перед вами 3 двери: за двумя козы, за одной мешок с деньгами.</p>

<h1>Ваш выбор:</h1>
<br />
<% @game.each_with_index do |value, i|%>
  <%= link_to image_tag('door.jpg', :class => "item-img"), edit_statistic_path(i) %>
<% end %>

app/views/statistics/show.html.erb
<h3>
  <% if @status == :won %>
    Вы выиграли!
  <% else %>
    Вы проиграли!
  <% end %>
</h3>
<br />

<% @game.each_with_index do |value, i|%>
  <%= image_tag(value + '.jpg', :class => "item-img") %>
<% end %>

<br />
<br />
<h3>Вероятность выигрыша (статистика сыгранных партий)</h3>
<table>
  <tr>
    <td>при смене двери</td>
    <td>при выборе той же двери</td>
  </tr>
  <tr>
    <td><%= calc_percent(@statistic.num_change, @statistic.num_change_won) %>%</td>
    <td><%= calc_percent(@statistic.num_not_change, @statistic.num_not_change_won) %>%</td>
  </tr>
</table>

<br />
<br />

<%= link_to 'Сыграть еще', root_path, class: 'btn btn-primary' %>